import sys
from . import parser

MODULE_BANNER = "/* THIS FILE WAS AUTOGENERATED FROM %s USING THE C4 TRANSPILER */\n"


def Translate(string, source):
  return MODULE_BANNER % source + parser.Parse(string, source).str


def main():
  if len(sys.argv) == 1:
    source = '<stdin>'
    string = sys.stdin.read()
  elif len(sys.argv) == 2:
    source = sys.argv[1]
    with open(sys.argv[1]) as f:
      string = f.read()
  else:
    print('Usage: python %s [source.c4]' % sys.argv[0])
    exit(1)

  sys.stdout.write(Translate(string, source))


if __name__ == '__main__':
  main()
